In [4]:
import numpy as np

In [5]:
gamma = 0.75 # discount factor
alpha = 0.9 # learning rate

In [6]:
location_to_state = {'A': 0, 
                     'B': 1, 
                     'C': 2,
                     'D': 3, 
                     'E': 4,
                     'F': 5, 
                     'G': 6, 
                     'H': 7,
                     'I': 8, 
                     'J': 9, 
                     'K': 10,
                     'L': 11
                     }

In [7]:
actions = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [8]:
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
            [1,0,1,0,0,1,0,0,0,0,0,0],
            [0,1,0,0,0,0,1,0,0,0,0,0],
            [0,0,0,0,0,0,0,1,0,0,0,0],
            [0,0,0,0,0,0,0,0,1,0,0,0],
            [0,1,0,0,0,0,0,0,0,1,0,0],
            [0,0,1,0,0,0,1000,1,0,0,0,0],
            [0,0,0,1,0,0,1,0,0,0,0,1],
            [0,0,0,0,1,0,0,0,0,1,0,0],
            [0,0,0,0,0,1,0,0,1,0,1,0],
            [0,0,0,0,0,0,0,0,0,1,0,1],
            [0,0,0,0,0,0,0,1,0,0,1,0]])

Building Solution with Q-Learning

In [9]:
# Initialization
Q = np.array(np.zeros([12, 12]))

In [10]:
# Implementation of Q-Learning process
for i in range(1000):
    current_state = np.random.randint(0, 12)
    playbale_actions = []
    for j in range(12):
        if R[current_state, j] > 0:
            playbale_actions.append(j)
    
    next_state = np.random.choice(playbale_actions)
    TD = R[current_state, next_state] + gamma*Q[next_state, np.argmax(Q[next_state, ])] - Q[current_state, next_state]

    Q[current_state, next_state] = Q[current_state, next_state] + alpha*TD

print("Q-Values: ")
print(Q.astype(int))

    


Q-Values: 
[[   0 1664    0    0    0    0    0    0    0    0    0    0]
 [1244    0 2235    0    0 1236    0    0    0    0    0    0]
 [   0 1664    0    0    0    0 2982    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2202    0    0    0    0]
 [   0    0    0    0    0    0    0    0  702    0    0    0]
 [   0 1664    0    0    0    0    0    0    0  933    0    0]
 [   0    0 2237    0    0    0 3975 2202    0    0    0    0]
 [   0    0    0 1652    0    0 2935    0    0    0    0 1652]
 [   0    0    0    0  527    0    0    0    0  934    0    0]
 [   0    0    0    0    0 1248    0    0  686    0 1240    0]
 [   0    0    0    0    0    0    0    0    0  935    0 1652]
 [   0    0    0    0    0    0    0 2202    0    0 1237    0]]


Find the best Route

In [13]:
# Creating a map from states to location using a dictionary
state_to_location = {state: location for location, state in location_to_state.items()}

In [17]:
# Creating the final function that will return the optimal route
def route(starting_location, ending_location):
    route = [starting_location]
    next_location = starting_location

    while (next_location != ending_location):
            starting_state = location_to_state[starting_location]
            next_state = np.argmax(Q[starting_state])
            next_location = state_to_location[next_state]
            route.append(next_location)
            starting_location = next_location
        
    return route

In [21]:
print("Route: ")
route('E', 'G')

Route: 


['E', 'I', 'J', 'F', 'B', 'C', 'G']