In [1]:
import gymnasium as gym
import numpy as np

In [2]:
env = gym.make("FrozenLake-v1")

In [3]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
alpha = 0.8
gamma = 0.9
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
reward_list = []

In [4]:
def state_to_index(state, shape):
    index = 0
    for i in range(len(shape)):
        index += state[i] * np.prod(shape[i+1:])
    return index

for i in range(num_episodes):
    state = env.reset()
    total_reward = 0
    done = False
    j = 0
    # Assuming env.observation_space.shape contains the shape of each dimension of the state space
    state_index = state_to_index(state, env.observation_space.shape)
    while j < 99:
        j += 1
        state_index = state_to_index(state, env.observation_space.shape)
        action = np.argmax(Q[state_index, :] + np.random.randn(1, env.action_space.n) * (1 / (i + 1)))
        new_state, reward, done, _, _ = env.step(action)
        new_state_index = state_to_index(new_state, env.observation_space.shape)
        Q[state_index, action] = Q[state_index, action] + alpha * (reward + gamma * np.max(Q[new_state_index, :]) - Q[state_index, action])
        total_reward += reward
        state = new_state
        if done:
            break
    reward_list.append(total_reward)


In [5]:
print ("Score over time: " +  str(sum(reward_list)/num_episodes))


Score over time: 0.0115


In [11]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[1.23372689e-09 5.11440080e-02 1.22314692e-03 1.01928931e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.